# Generated by Django 4.2.13 on 2025-12-08 17:45

from django.db import migrations, models


def migrate_full_name_to_first_last(apps, schema_editor):
    """Migrate full_name to first_name and last_name"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if user.full_name:
            parts = user.full_name.strip().split(maxsplit=1)
            user.first_name = parts[0] if parts else ""
            user.last_name = parts[1] if len(parts) > 1 else ""
            user.save()


def reverse_migrate_first_last_to_full_name(apps, schema_editor):
    """Reverse migration: combine first_name and last_name back to full_name"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.full_name = f"{user.first_name} {user.last_name}".strip()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Migrate data
        migrations.RunPython(migrate_full_name_to_first_last, reverse_migrate_first_last_to_full_name),
        # Remove old field
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
