# Generated by Django 4.2.13 on 2025-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task_notification_comment_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='honeymoonitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='honeymoonitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moodboarditem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moodboarditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
